
hello: hello.o greeting.o factorial.o
	g++ hello.o greeting.o factorial.o -o hello

hello.o: hello.cxx
	g++ -c hello.cxx

greeting.o: greeting.cxx
	g++ -c greeting.cxx

factorial.o: factorial.cxx
	g++ -c factorial.cxx

